import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { AppSidebar } from "../components/AppSidebar";
import { Navbar } from "../components/layouts/Navbar";
import { SearchProvider } from "@/src/hooks/use-search";
import { Suspense } from "react";

const IBMPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-IBMPlexSans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Podcast Thmanyah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${IBMPlexSansArabic.variable} bg-bg1`}>
        <Suspense>
          <SearchProvider>
            <SidebarProvider>
              <div className="flex h-screen overflow-hidden w-full ">
                <AppSidebar />
                <div className="flex-1 flex flex-col overflow-hidden ">
                  <Navbar />
                  <main className="flex-1 overflow-y-auto">{children}</main>
                </div>
              </div>
            </SidebarProvider>
          </SearchProvider>
        </Suspense>
      </body>
    </html>
  );
}
